// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSystem.proto

package org.fs.proto;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.fs.proto.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileName = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();
}
