// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSystem.proto

package org.fs.proto;

/**
 * Protobuf type {@code org.fs.proto.FilesList}
 */
public  final class FilesList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.fs.proto.FilesList)
    FilesListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FilesList.newBuilder() to construct.
  private FilesList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FilesList() {
    files_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FilesList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FilesList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              files_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            files_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        files_ = files_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_FilesList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_FilesList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.fs.proto.FilesList.class, org.fs.proto.FilesList.Builder.class);
  }

  public static final int FILES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList files_;
  /**
   * <code>repeated string files = 1;</code>
   * @return A list containing the files.
   */
  public com.google.protobuf.ProtocolStringList
      getFilesList() {
    return files_;
  }
  /**
   * <code>repeated string files = 1;</code>
   * @return The count of files.
   */
  public int getFilesCount() {
    return files_.size();
  }
  /**
   * <code>repeated string files = 1;</code>
   * @param index The index of the element to return.
   * @return The files at the given index.
   */
  public java.lang.String getFiles(int index) {
    return files_.get(index);
  }
  /**
   * <code>repeated string files = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the files at the given index.
   */
  public com.google.protobuf.ByteString
      getFilesBytes(int index) {
    return files_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < files_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, files_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < files_.size(); i++) {
        dataSize += computeStringSizeNoTag(files_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFilesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.fs.proto.FilesList)) {
      return super.equals(obj);
    }
    org.fs.proto.FilesList other = (org.fs.proto.FilesList) obj;

    if (!getFilesList()
        .equals(other.getFilesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFilesCount() > 0) {
      hash = (37 * hash) + FILES_FIELD_NUMBER;
      hash = (53 * hash) + getFilesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.fs.proto.FilesList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fs.proto.FilesList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fs.proto.FilesList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fs.proto.FilesList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fs.proto.FilesList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fs.proto.FilesList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fs.proto.FilesList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fs.proto.FilesList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fs.proto.FilesList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.fs.proto.FilesList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fs.proto.FilesList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fs.proto.FilesList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.fs.proto.FilesList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.fs.proto.FilesList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.fs.proto.FilesList)
      org.fs.proto.FilesListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_FilesList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_FilesList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fs.proto.FilesList.class, org.fs.proto.FilesList.Builder.class);
    }

    // Construct using org.fs.proto.FilesList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      files_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_FilesList_descriptor;
    }

    @java.lang.Override
    public org.fs.proto.FilesList getDefaultInstanceForType() {
      return org.fs.proto.FilesList.getDefaultInstance();
    }

    @java.lang.Override
    public org.fs.proto.FilesList build() {
      org.fs.proto.FilesList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.fs.proto.FilesList buildPartial() {
      org.fs.proto.FilesList result = new org.fs.proto.FilesList(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        files_ = files_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.files_ = files_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.fs.proto.FilesList) {
        return mergeFrom((org.fs.proto.FilesList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.fs.proto.FilesList other) {
      if (other == org.fs.proto.FilesList.getDefaultInstance()) return this;
      if (!other.files_.isEmpty()) {
        if (files_.isEmpty()) {
          files_ = other.files_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFilesIsMutable();
          files_.addAll(other.files_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.fs.proto.FilesList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.fs.proto.FilesList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList files_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFilesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        files_ = new com.google.protobuf.LazyStringArrayList(files_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string files = 1;</code>
     * @return A list containing the files.
     */
    public com.google.protobuf.ProtocolStringList
        getFilesList() {
      return files_.getUnmodifiableView();
    }
    /**
     * <code>repeated string files = 1;</code>
     * @return The count of files.
     */
    public int getFilesCount() {
      return files_.size();
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param index The index of the element to return.
     * @return The files at the given index.
     */
    public java.lang.String getFiles(int index) {
      return files_.get(index);
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the files at the given index.
     */
    public com.google.protobuf.ByteString
        getFilesBytes(int index) {
      return files_.getByteString(index);
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param index The index to set the value at.
     * @param value The files to set.
     * @return This builder for chaining.
     */
    public Builder setFiles(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFilesIsMutable();
      files_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param value The files to add.
     * @return This builder for chaining.
     */
    public Builder addFiles(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFilesIsMutable();
      files_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param values The files to add.
     * @return This builder for chaining.
     */
    public Builder addAllFiles(
        java.lang.Iterable<java.lang.String> values) {
      ensureFilesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, files_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFiles() {
      files_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 1;</code>
     * @param value The bytes of the files to add.
     * @return This builder for chaining.
     */
    public Builder addFilesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFilesIsMutable();
      files_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.fs.proto.FilesList)
  }

  // @@protoc_insertion_point(class_scope:org.fs.proto.FilesList)
  private static final org.fs.proto.FilesList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.fs.proto.FilesList();
  }

  public static org.fs.proto.FilesList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FilesList>
      PARSER = new com.google.protobuf.AbstractParser<FilesList>() {
    @java.lang.Override
    public FilesList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FilesList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FilesList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FilesList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.fs.proto.FilesList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

