// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSystem.proto

package org.fs.proto;

public final class FileSystemOuterClass {
  private FileSystemOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fs_proto_FileContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fs_proto_FileContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fs_proto_UploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fs_proto_UploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fs_proto_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fs_proto_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fs_proto_RenameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fs_proto_RenameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fs_proto_OpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fs_proto_OpResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fs_proto_FilesList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fs_proto_FilesList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020fileSystem.proto\022\014org.fs.proto\032\033google" +
      "/protobuf/empty.proto\"\036\n\013FileContent\022\017\n\007" +
      "content\030\001 \001(\014\"Q\n\rUploadRequest\022\020\n\010fileNa" +
      "me\030\001 \001(\t\022.\n\013fileContent\030\002 \001(\0132\031.org.fs.p" +
      "roto.FileContent\"!\n\rDeleteRequest\022\020\n\010fil" +
      "eName\030\001 \001(\t\"9\n\rRenameRequest\022\023\n\013oldFileN" +
      "ame\030\001 \001(\t\022\023\n\013newFileName\030\002 \001(\t\"\034\n\nOpResp" +
      "onse\022\016\n\006status\030\001 \001(\t\"\032\n\tFilesList\022\r\n\005fil" +
      "es\030\001 \003(\t2\224\002\n\nFileSystem\022A\n\006upload\022\033.org." +
      "fs.proto.UploadRequest\032\030.org.fs.proto.Op" +
      "Response\"\000\022A\n\006delete\022\033.org.fs.proto.Dele" +
      "teRequest\032\030.org.fs.proto.OpResponse\"\000\022A\n" +
      "\006rename\022\033.org.fs.proto.RenameRequest\032\030.o" +
      "rg.fs.proto.OpResponse\"\000\022=\n\010getFiles\022\026.g" +
      "oogle.protobuf.Empty\032\027.org.fs.proto.File" +
      "sList\"\000B\020\n\014org.fs.protoP\001P\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_org_fs_proto_FileContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_fs_proto_FileContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fs_proto_FileContent_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_org_fs_proto_UploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_fs_proto_UploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fs_proto_UploadRequest_descriptor,
        new java.lang.String[] { "FileName", "FileContent", });
    internal_static_org_fs_proto_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_fs_proto_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fs_proto_DeleteRequest_descriptor,
        new java.lang.String[] { "FileName", });
    internal_static_org_fs_proto_RenameRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_fs_proto_RenameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fs_proto_RenameRequest_descriptor,
        new java.lang.String[] { "OldFileName", "NewFileName", });
    internal_static_org_fs_proto_OpResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_fs_proto_OpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fs_proto_OpResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_org_fs_proto_FilesList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_fs_proto_FilesList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fs_proto_FilesList_descriptor,
        new java.lang.String[] { "Files", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
