// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSystem.proto

package org.fs.proto;

public interface OpResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.fs.proto.OpResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
