// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSystem.proto

package org.fs.proto;

public interface UploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.fs.proto.UploadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileName = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>.org.fs.proto.FileContent fileContent = 2;</code>
   * @return Whether the fileContent field is set.
   */
  boolean hasFileContent();
  /**
   * <code>.org.fs.proto.FileContent fileContent = 2;</code>
   * @return The fileContent.
   */
  org.fs.proto.FileContent getFileContent();
  /**
   * <code>.org.fs.proto.FileContent fileContent = 2;</code>
   */
  org.fs.proto.FileContentOrBuilder getFileContentOrBuilder();
}
