// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSystem.proto

package org.fs.proto;

/**
 * Protobuf type {@code org.fs.proto.UploadRequest}
 */
public  final class UploadRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.fs.proto.UploadRequest)
    UploadRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UploadRequest.newBuilder() to construct.
  private UploadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UploadRequest() {
    fileName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UploadRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UploadRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fileName_ = s;
            break;
          }
          case 18: {
            org.fs.proto.FileContent.Builder subBuilder = null;
            if (fileContent_ != null) {
              subBuilder = fileContent_.toBuilder();
            }
            fileContent_ = input.readMessage(org.fs.proto.FileContent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fileContent_);
              fileContent_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_UploadRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_UploadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.fs.proto.UploadRequest.class, org.fs.proto.UploadRequest.Builder.class);
  }

  public static final int FILENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object fileName_;
  /**
   * <code>string fileName = 1;</code>
   * @return The fileName.
   */
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string fileName = 1;</code>
   * @return The bytes for fileName.
   */
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILECONTENT_FIELD_NUMBER = 2;
  private org.fs.proto.FileContent fileContent_;
  /**
   * <code>.org.fs.proto.FileContent fileContent = 2;</code>
   * @return Whether the fileContent field is set.
   */
  public boolean hasFileContent() {
    return fileContent_ != null;
  }
  /**
   * <code>.org.fs.proto.FileContent fileContent = 2;</code>
   * @return The fileContent.
   */
  public org.fs.proto.FileContent getFileContent() {
    return fileContent_ == null ? org.fs.proto.FileContent.getDefaultInstance() : fileContent_;
  }
  /**
   * <code>.org.fs.proto.FileContent fileContent = 2;</code>
   */
  public org.fs.proto.FileContentOrBuilder getFileContentOrBuilder() {
    return getFileContent();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
    }
    if (fileContent_ != null) {
      output.writeMessage(2, getFileContent());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
    }
    if (fileContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFileContent());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.fs.proto.UploadRequest)) {
      return super.equals(obj);
    }
    org.fs.proto.UploadRequest other = (org.fs.proto.UploadRequest) obj;

    if (!getFileName()
        .equals(other.getFileName())) return false;
    if (hasFileContent() != other.hasFileContent()) return false;
    if (hasFileContent()) {
      if (!getFileContent()
          .equals(other.getFileContent())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    if (hasFileContent()) {
      hash = (37 * hash) + FILECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getFileContent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.fs.proto.UploadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fs.proto.UploadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fs.proto.UploadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fs.proto.UploadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fs.proto.UploadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fs.proto.UploadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fs.proto.UploadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fs.proto.UploadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fs.proto.UploadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.fs.proto.UploadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fs.proto.UploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fs.proto.UploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.fs.proto.UploadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.fs.proto.UploadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.fs.proto.UploadRequest)
      org.fs.proto.UploadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_UploadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_UploadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fs.proto.UploadRequest.class, org.fs.proto.UploadRequest.Builder.class);
    }

    // Construct using org.fs.proto.UploadRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      fileName_ = "";

      if (fileContentBuilder_ == null) {
        fileContent_ = null;
      } else {
        fileContent_ = null;
        fileContentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.fs.proto.FileSystemOuterClass.internal_static_org_fs_proto_UploadRequest_descriptor;
    }

    @java.lang.Override
    public org.fs.proto.UploadRequest getDefaultInstanceForType() {
      return org.fs.proto.UploadRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.fs.proto.UploadRequest build() {
      org.fs.proto.UploadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.fs.proto.UploadRequest buildPartial() {
      org.fs.proto.UploadRequest result = new org.fs.proto.UploadRequest(this);
      result.fileName_ = fileName_;
      if (fileContentBuilder_ == null) {
        result.fileContent_ = fileContent_;
      } else {
        result.fileContent_ = fileContentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.fs.proto.UploadRequest) {
        return mergeFrom((org.fs.proto.UploadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.fs.proto.UploadRequest other) {
      if (other == org.fs.proto.UploadRequest.getDefaultInstance()) return this;
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        onChanged();
      }
      if (other.hasFileContent()) {
        mergeFileContent(other.getFileContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.fs.proto.UploadRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.fs.proto.UploadRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object fileName_ = "";
    /**
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      
      fileName_ = getDefaultInstance().getFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 1;</code>
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileName_ = value;
      onChanged();
      return this;
    }

    private org.fs.proto.FileContent fileContent_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.fs.proto.FileContent, org.fs.proto.FileContent.Builder, org.fs.proto.FileContentOrBuilder> fileContentBuilder_;
    /**
     * <code>.org.fs.proto.FileContent fileContent = 2;</code>
     * @return Whether the fileContent field is set.
     */
    public boolean hasFileContent() {
      return fileContentBuilder_ != null || fileContent_ != null;
    }
    /**
     * <code>.org.fs.proto.FileContent fileContent = 2;</code>
     * @return The fileContent.
     */
    public org.fs.proto.FileContent getFileContent() {
      if (fileContentBuilder_ == null) {
        return fileContent_ == null ? org.fs.proto.FileContent.getDefaultInstance() : fileContent_;
      } else {
        return fileContentBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.fs.proto.FileContent fileContent = 2;</code>
     */
    public Builder setFileContent(org.fs.proto.FileContent value) {
      if (fileContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fileContent_ = value;
        onChanged();
      } else {
        fileContentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.fs.proto.FileContent fileContent = 2;</code>
     */
    public Builder setFileContent(
        org.fs.proto.FileContent.Builder builderForValue) {
      if (fileContentBuilder_ == null) {
        fileContent_ = builderForValue.build();
        onChanged();
      } else {
        fileContentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.fs.proto.FileContent fileContent = 2;</code>
     */
    public Builder mergeFileContent(org.fs.proto.FileContent value) {
      if (fileContentBuilder_ == null) {
        if (fileContent_ != null) {
          fileContent_ =
            org.fs.proto.FileContent.newBuilder(fileContent_).mergeFrom(value).buildPartial();
        } else {
          fileContent_ = value;
        }
        onChanged();
      } else {
        fileContentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.fs.proto.FileContent fileContent = 2;</code>
     */
    public Builder clearFileContent() {
      if (fileContentBuilder_ == null) {
        fileContent_ = null;
        onChanged();
      } else {
        fileContent_ = null;
        fileContentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.fs.proto.FileContent fileContent = 2;</code>
     */
    public org.fs.proto.FileContent.Builder getFileContentBuilder() {
      
      onChanged();
      return getFileContentFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.fs.proto.FileContent fileContent = 2;</code>
     */
    public org.fs.proto.FileContentOrBuilder getFileContentOrBuilder() {
      if (fileContentBuilder_ != null) {
        return fileContentBuilder_.getMessageOrBuilder();
      } else {
        return fileContent_ == null ?
            org.fs.proto.FileContent.getDefaultInstance() : fileContent_;
      }
    }
    /**
     * <code>.org.fs.proto.FileContent fileContent = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.fs.proto.FileContent, org.fs.proto.FileContent.Builder, org.fs.proto.FileContentOrBuilder> 
        getFileContentFieldBuilder() {
      if (fileContentBuilder_ == null) {
        fileContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.fs.proto.FileContent, org.fs.proto.FileContent.Builder, org.fs.proto.FileContentOrBuilder>(
                getFileContent(),
                getParentForChildren(),
                isClean());
        fileContent_ = null;
      }
      return fileContentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.fs.proto.UploadRequest)
  }

  // @@protoc_insertion_point(class_scope:org.fs.proto.UploadRequest)
  private static final org.fs.proto.UploadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.fs.proto.UploadRequest();
  }

  public static org.fs.proto.UploadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UploadRequest>
      PARSER = new com.google.protobuf.AbstractParser<UploadRequest>() {
    @java.lang.Override
    public UploadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UploadRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UploadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UploadRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.fs.proto.UploadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

