// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: as.proto

package org.as.proto;

public interface AddResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.as.proto.AddResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum = 1;</code>
   * @return The sum.
   */
  int getSum();
}
