// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: as.proto

package org.as.proto;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.as.proto.AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 i = 1;</code>
   * @return The i.
   */
  int getI();

  /**
   * <code>int32 j = 2;</code>
   * @return The j.
   */
  int getJ();
}
