// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: as.proto

package org.as.proto;

/**
 * Protobuf enum {@code org.as.proto.Algorithm}
 */
public enum Algorithm
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>BUBBLE_SORT = 0;</code>
   */
  BUBBLE_SORT(0),
  /**
   * <code>INSERTION_SORT = 1;</code>
   */
  INSERTION_SORT(1),
  /**
   * <code>SELECTION_SORT = 2;</code>
   */
  SELECTION_SORT(2),
  /**
   * <code>MERGE_SORT = 3;</code>
   */
  MERGE_SORT(3),
  /**
   * <code>QUICK_SORT = 4;</code>
   */
  QUICK_SORT(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>BUBBLE_SORT = 0;</code>
   */
  public static final int BUBBLE_SORT_VALUE = 0;
  /**
   * <code>INSERTION_SORT = 1;</code>
   */
  public static final int INSERTION_SORT_VALUE = 1;
  /**
   * <code>SELECTION_SORT = 2;</code>
   */
  public static final int SELECTION_SORT_VALUE = 2;
  /**
   * <code>MERGE_SORT = 3;</code>
   */
  public static final int MERGE_SORT_VALUE = 3;
  /**
   * <code>QUICK_SORT = 4;</code>
   */
  public static final int QUICK_SORT_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Algorithm valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Algorithm forNumber(int value) {
    switch (value) {
      case 0: return BUBBLE_SORT;
      case 1: return INSERTION_SORT;
      case 2: return SELECTION_SORT;
      case 3: return MERGE_SORT;
      case 4: return QUICK_SORT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Algorithm> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Algorithm>() {
          public Algorithm findValueByNumber(int number) {
            return Algorithm.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.as.proto.As.getDescriptor().getEnumTypes().get(0);
  }

  private static final Algorithm[] VALUES = values();

  public static Algorithm valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Algorithm(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.as.proto.Algorithm)
}

