// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: as.proto

package org.as.proto;

public final class As {
  private As() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_as_proto_AddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_as_proto_AddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_as_proto_AddResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_as_proto_AddResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_as_proto_SortRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_as_proto_SortRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_as_proto_SortResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_as_proto_SortResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010as.proto\022\014org.as.proto\"\"\n\nAddRequest\022\t" +
      "\n\001i\030\001 \001(\005\022\t\n\001j\030\002 \001(\005\"\032\n\013AddResponse\022\013\n\003s" +
      "um\030\001 \001(\005\"H\n\013SortRequest\022*\n\talgorithm\030\001 \001" +
      "(\0162\027.org.as.proto.Algorithm\022\r\n\005array\030\002 \003" +
      "(\005\".\n\014SortResponse\022\017\n\007message\030\001 \001(\t\022\r\n\005a" +
      "rray\030\002 \003(\005*d\n\tAlgorithm\022\017\n\013BUBBLE_SORT\020\000" +
      "\022\022\n\016INSERTION_SORT\020\001\022\022\n\016SELECTION_SORT\020\002" +
      "\022\016\n\nMERGE_SORT\020\003\022\016\n\nQUICK_SORT\020\0042\210\001\n\007Add" +
      "Sort\022<\n\003add\022\030.org.as.proto.AddRequest\032\031." +
      "org.as.proto.AddResponse\"\000\022?\n\004sort\022\031.org" +
      ".as.proto.SortRequest\032\032.org.as.proto.Sor" +
      "tResponse\"\000B\020\n\014org.as.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_as_proto_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_as_proto_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_as_proto_AddRequest_descriptor,
        new java.lang.String[] { "I", "J", });
    internal_static_org_as_proto_AddResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_as_proto_AddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_as_proto_AddResponse_descriptor,
        new java.lang.String[] { "Sum", });
    internal_static_org_as_proto_SortRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_as_proto_SortRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_as_proto_SortRequest_descriptor,
        new java.lang.String[] { "Algorithm", "Array", });
    internal_static_org_as_proto_SortResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_as_proto_SortResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_as_proto_SortResponse_descriptor,
        new java.lang.String[] { "Message", "Array", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
