// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: as.proto

package org.as.proto;

/**
 * Protobuf type {@code org.as.proto.SortRequest}
 */
public  final class SortRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.as.proto.SortRequest)
    SortRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SortRequest.newBuilder() to construct.
  private SortRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SortRequest() {
    algorithm_ = 0;
    array_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SortRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SortRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            algorithm_ = rawValue;
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              array_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            array_.addInt(input.readInt32());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              array_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              array_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        array_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.as.proto.As.internal_static_org_as_proto_SortRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.as.proto.As.internal_static_org_as_proto_SortRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.as.proto.SortRequest.class, org.as.proto.SortRequest.Builder.class);
  }

  public static final int ALGORITHM_FIELD_NUMBER = 1;
  private int algorithm_;
  /**
   * <code>.org.as.proto.Algorithm algorithm = 1;</code>
   * @return The enum numeric value on the wire for algorithm.
   */
  public int getAlgorithmValue() {
    return algorithm_;
  }
  /**
   * <code>.org.as.proto.Algorithm algorithm = 1;</code>
   * @return The algorithm.
   */
  public org.as.proto.Algorithm getAlgorithm() {
    @SuppressWarnings("deprecation")
    org.as.proto.Algorithm result = org.as.proto.Algorithm.valueOf(algorithm_);
    return result == null ? org.as.proto.Algorithm.UNRECOGNIZED : result;
  }

  public static final int ARRAY_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.IntList array_;
  /**
   * <code>repeated int32 array = 2;</code>
   * @return A list containing the array.
   */
  public java.util.List<java.lang.Integer>
      getArrayList() {
    return array_;
  }
  /**
   * <code>repeated int32 array = 2;</code>
   * @return The count of array.
   */
  public int getArrayCount() {
    return array_.size();
  }
  /**
   * <code>repeated int32 array = 2;</code>
   * @param index The index of the element to return.
   * @return The array at the given index.
   */
  public int getArray(int index) {
    return array_.getInt(index);
  }
  private int arrayMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (algorithm_ != org.as.proto.Algorithm.BUBBLE_SORT.getNumber()) {
      output.writeEnum(1, algorithm_);
    }
    if (getArrayList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(arrayMemoizedSerializedSize);
    }
    for (int i = 0; i < array_.size(); i++) {
      output.writeInt32NoTag(array_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (algorithm_ != org.as.proto.Algorithm.BUBBLE_SORT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, algorithm_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < array_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(array_.getInt(i));
      }
      size += dataSize;
      if (!getArrayList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      arrayMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.as.proto.SortRequest)) {
      return super.equals(obj);
    }
    org.as.proto.SortRequest other = (org.as.proto.SortRequest) obj;

    if (algorithm_ != other.algorithm_) return false;
    if (!getArrayList()
        .equals(other.getArrayList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
    hash = (53 * hash) + algorithm_;
    if (getArrayCount() > 0) {
      hash = (37 * hash) + ARRAY_FIELD_NUMBER;
      hash = (53 * hash) + getArrayList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.as.proto.SortRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.as.proto.SortRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.as.proto.SortRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.as.proto.SortRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.as.proto.SortRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.as.proto.SortRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.as.proto.SortRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.as.proto.SortRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.as.proto.SortRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.as.proto.SortRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.as.proto.SortRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.as.proto.SortRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.as.proto.SortRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.as.proto.SortRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.as.proto.SortRequest)
      org.as.proto.SortRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.as.proto.As.internal_static_org_as_proto_SortRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.as.proto.As.internal_static_org_as_proto_SortRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.as.proto.SortRequest.class, org.as.proto.SortRequest.Builder.class);
    }

    // Construct using org.as.proto.SortRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      algorithm_ = 0;

      array_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.as.proto.As.internal_static_org_as_proto_SortRequest_descriptor;
    }

    @java.lang.Override
    public org.as.proto.SortRequest getDefaultInstanceForType() {
      return org.as.proto.SortRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.as.proto.SortRequest build() {
      org.as.proto.SortRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.as.proto.SortRequest buildPartial() {
      org.as.proto.SortRequest result = new org.as.proto.SortRequest(this);
      int from_bitField0_ = bitField0_;
      result.algorithm_ = algorithm_;
      if (((bitField0_ & 0x00000001) != 0)) {
        array_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.array_ = array_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.as.proto.SortRequest) {
        return mergeFrom((org.as.proto.SortRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.as.proto.SortRequest other) {
      if (other == org.as.proto.SortRequest.getDefaultInstance()) return this;
      if (other.algorithm_ != 0) {
        setAlgorithmValue(other.getAlgorithmValue());
      }
      if (!other.array_.isEmpty()) {
        if (array_.isEmpty()) {
          array_ = other.array_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureArrayIsMutable();
          array_.addAll(other.array_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.as.proto.SortRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.as.proto.SortRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int algorithm_ = 0;
    /**
     * <code>.org.as.proto.Algorithm algorithm = 1;</code>
     * @return The enum numeric value on the wire for algorithm.
     */
    public int getAlgorithmValue() {
      return algorithm_;
    }
    /**
     * <code>.org.as.proto.Algorithm algorithm = 1;</code>
     * @param value The enum numeric value on the wire for algorithm to set.
     * @return This builder for chaining.
     */
    public Builder setAlgorithmValue(int value) {
      algorithm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.org.as.proto.Algorithm algorithm = 1;</code>
     * @return The algorithm.
     */
    public org.as.proto.Algorithm getAlgorithm() {
      @SuppressWarnings("deprecation")
      org.as.proto.Algorithm result = org.as.proto.Algorithm.valueOf(algorithm_);
      return result == null ? org.as.proto.Algorithm.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.as.proto.Algorithm algorithm = 1;</code>
     * @param value The algorithm to set.
     * @return This builder for chaining.
     */
    public Builder setAlgorithm(org.as.proto.Algorithm value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      algorithm_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.as.proto.Algorithm algorithm = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlgorithm() {
      
      algorithm_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList array_ = emptyIntList();
    private void ensureArrayIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        array_ = mutableCopy(array_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 array = 2;</code>
     * @return A list containing the array.
     */
    public java.util.List<java.lang.Integer>
        getArrayList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(array_) : array_;
    }
    /**
     * <code>repeated int32 array = 2;</code>
     * @return The count of array.
     */
    public int getArrayCount() {
      return array_.size();
    }
    /**
     * <code>repeated int32 array = 2;</code>
     * @param index The index of the element to return.
     * @return The array at the given index.
     */
    public int getArray(int index) {
      return array_.getInt(index);
    }
    /**
     * <code>repeated int32 array = 2;</code>
     * @param index The index to set the value at.
     * @param value The array to set.
     * @return This builder for chaining.
     */
    public Builder setArray(
        int index, int value) {
      ensureArrayIsMutable();
      array_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 array = 2;</code>
     * @param value The array to add.
     * @return This builder for chaining.
     */
    public Builder addArray(int value) {
      ensureArrayIsMutable();
      array_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 array = 2;</code>
     * @param values The array to add.
     * @return This builder for chaining.
     */
    public Builder addAllArray(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureArrayIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, array_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 array = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearArray() {
      array_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.as.proto.SortRequest)
  }

  // @@protoc_insertion_point(class_scope:org.as.proto.SortRequest)
  private static final org.as.proto.SortRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.as.proto.SortRequest();
  }

  public static org.as.proto.SortRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SortRequest>
      PARSER = new com.google.protobuf.AbstractParser<SortRequest>() {
    @java.lang.Override
    public SortRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SortRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SortRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SortRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.as.proto.SortRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

