// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: as.proto

package org.as.proto;

public interface SortResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.as.proto.SortResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated int32 array = 2;</code>
   * @return A list containing the array.
   */
  java.util.List<java.lang.Integer> getArrayList();
  /**
   * <code>repeated int32 array = 2;</code>
   * @return The count of array.
   */
  int getArrayCount();
  /**
   * <code>repeated int32 array = 2;</code>
   * @param index The index of the element to return.
   * @return The array at the given index.
   */
  int getArray(int index);
}
