// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: as.proto

package org.as.proto;

public interface SortRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.as.proto.SortRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.as.proto.Algorithm algorithm = 1;</code>
   * @return The enum numeric value on the wire for algorithm.
   */
  int getAlgorithmValue();
  /**
   * <code>.org.as.proto.Algorithm algorithm = 1;</code>
   * @return The algorithm.
   */
  org.as.proto.Algorithm getAlgorithm();

  /**
   * <code>repeated int32 array = 2;</code>
   * @return A list containing the array.
   */
  java.util.List<java.lang.Integer> getArrayList();
  /**
   * <code>repeated int32 array = 2;</code>
   * @return The count of array.
   */
  int getArrayCount();
  /**
   * <code>repeated int32 array = 2;</code>
   * @param index The index of the element to return.
   * @return The array at the given index.
   */
  int getArray(int index);
}
