// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSync.proto

package org.sync.proto;

public interface FileContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sync.proto.FileContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes content = 1;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
