// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSync.proto

package org.sync.proto;

public interface OperationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sync.proto.OperationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.org.sync.proto.Status status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.org.sync.proto.Status status = 2;</code>
   * @return The status.
   */
  org.sync.proto.Status getStatus();
}
