// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSync.proto

package org.sync.proto;

/**
 * Protobuf type {@code org.sync.proto.RenameRequest}
 */
public  final class RenameRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.sync.proto.RenameRequest)
    RenameRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RenameRequest.newBuilder() to construct.
  private RenameRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RenameRequest() {
    oldFileName_ = "";
    newFileName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RenameRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RenameRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            oldFileName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            newFileName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.sync.proto.FileSyncOuterClass.internal_static_org_sync_proto_RenameRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.sync.proto.FileSyncOuterClass.internal_static_org_sync_proto_RenameRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.sync.proto.RenameRequest.class, org.sync.proto.RenameRequest.Builder.class);
  }

  public static final int OLDFILENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object oldFileName_;
  /**
   * <code>string oldFileName = 1;</code>
   * @return The oldFileName.
   */
  public java.lang.String getOldFileName() {
    java.lang.Object ref = oldFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      oldFileName_ = s;
      return s;
    }
  }
  /**
   * <code>string oldFileName = 1;</code>
   * @return The bytes for oldFileName.
   */
  public com.google.protobuf.ByteString
      getOldFileNameBytes() {
    java.lang.Object ref = oldFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      oldFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEWFILENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object newFileName_;
  /**
   * <code>string newFileName = 2;</code>
   * @return The newFileName.
   */
  public java.lang.String getNewFileName() {
    java.lang.Object ref = newFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newFileName_ = s;
      return s;
    }
  }
  /**
   * <code>string newFileName = 2;</code>
   * @return The bytes for newFileName.
   */
  public com.google.protobuf.ByteString
      getNewFileNameBytes() {
    java.lang.Object ref = newFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOldFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, oldFileName_);
    }
    if (!getNewFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newFileName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOldFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, oldFileName_);
    }
    if (!getNewFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newFileName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.sync.proto.RenameRequest)) {
      return super.equals(obj);
    }
    org.sync.proto.RenameRequest other = (org.sync.proto.RenameRequest) obj;

    if (!getOldFileName()
        .equals(other.getOldFileName())) return false;
    if (!getNewFileName()
        .equals(other.getNewFileName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OLDFILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getOldFileName().hashCode();
    hash = (37 * hash) + NEWFILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getNewFileName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.sync.proto.RenameRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sync.proto.RenameRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sync.proto.RenameRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sync.proto.RenameRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sync.proto.RenameRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sync.proto.RenameRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sync.proto.RenameRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sync.proto.RenameRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sync.proto.RenameRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.sync.proto.RenameRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sync.proto.RenameRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sync.proto.RenameRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.sync.proto.RenameRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.sync.proto.RenameRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.sync.proto.RenameRequest)
      org.sync.proto.RenameRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sync.proto.FileSyncOuterClass.internal_static_org_sync_proto_RenameRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sync.proto.FileSyncOuterClass.internal_static_org_sync_proto_RenameRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sync.proto.RenameRequest.class, org.sync.proto.RenameRequest.Builder.class);
    }

    // Construct using org.sync.proto.RenameRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      oldFileName_ = "";

      newFileName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.sync.proto.FileSyncOuterClass.internal_static_org_sync_proto_RenameRequest_descriptor;
    }

    @java.lang.Override
    public org.sync.proto.RenameRequest getDefaultInstanceForType() {
      return org.sync.proto.RenameRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.sync.proto.RenameRequest build() {
      org.sync.proto.RenameRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.sync.proto.RenameRequest buildPartial() {
      org.sync.proto.RenameRequest result = new org.sync.proto.RenameRequest(this);
      result.oldFileName_ = oldFileName_;
      result.newFileName_ = newFileName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.sync.proto.RenameRequest) {
        return mergeFrom((org.sync.proto.RenameRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.sync.proto.RenameRequest other) {
      if (other == org.sync.proto.RenameRequest.getDefaultInstance()) return this;
      if (!other.getOldFileName().isEmpty()) {
        oldFileName_ = other.oldFileName_;
        onChanged();
      }
      if (!other.getNewFileName().isEmpty()) {
        newFileName_ = other.newFileName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.sync.proto.RenameRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.sync.proto.RenameRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object oldFileName_ = "";
    /**
     * <code>string oldFileName = 1;</code>
     * @return The oldFileName.
     */
    public java.lang.String getOldFileName() {
      java.lang.Object ref = oldFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oldFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string oldFileName = 1;</code>
     * @return The bytes for oldFileName.
     */
    public com.google.protobuf.ByteString
        getOldFileNameBytes() {
      java.lang.Object ref = oldFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string oldFileName = 1;</code>
     * @param value The oldFileName to set.
     * @return This builder for chaining.
     */
    public Builder setOldFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      oldFileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string oldFileName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOldFileName() {
      
      oldFileName_ = getDefaultInstance().getOldFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string oldFileName = 1;</code>
     * @param value The bytes for oldFileName to set.
     * @return This builder for chaining.
     */
    public Builder setOldFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      oldFileName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object newFileName_ = "";
    /**
     * <code>string newFileName = 2;</code>
     * @return The newFileName.
     */
    public java.lang.String getNewFileName() {
      java.lang.Object ref = newFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string newFileName = 2;</code>
     * @return The bytes for newFileName.
     */
    public com.google.protobuf.ByteString
        getNewFileNameBytes() {
      java.lang.Object ref = newFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string newFileName = 2;</code>
     * @param value The newFileName to set.
     * @return This builder for chaining.
     */
    public Builder setNewFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newFileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string newFileName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewFileName() {
      
      newFileName_ = getDefaultInstance().getNewFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string newFileName = 2;</code>
     * @param value The bytes for newFileName to set.
     * @return This builder for chaining.
     */
    public Builder setNewFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newFileName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.sync.proto.RenameRequest)
  }

  // @@protoc_insertion_point(class_scope:org.sync.proto.RenameRequest)
  private static final org.sync.proto.RenameRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.sync.proto.RenameRequest();
  }

  public static org.sync.proto.RenameRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RenameRequest>
      PARSER = new com.google.protobuf.AbstractParser<RenameRequest>() {
    @java.lang.Override
    public RenameRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RenameRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RenameRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RenameRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.sync.proto.RenameRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

