// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileSync.proto

package org.sync.proto;

public interface RenameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.sync.proto.RenameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string oldFileName = 1;</code>
   * @return The oldFileName.
   */
  java.lang.String getOldFileName();
  /**
   * <code>string oldFileName = 1;</code>
   * @return The bytes for oldFileName.
   */
  com.google.protobuf.ByteString
      getOldFileNameBytes();

  /**
   * <code>string newFileName = 2;</code>
   * @return The newFileName.
   */
  java.lang.String getNewFileName();
  /**
   * <code>string newFileName = 2;</code>
   * @return The bytes for newFileName.
   */
  com.google.protobuf.ByteString
      getNewFileNameBytes();
}
